[versions]
androidGradlePlugin = "8.1.4"
coreKtx = "1.10.0"
glide = "4.11.0"
kotlin = "1.9.0"
java = "18"
leanback = "1.0.0"
supportAnnotations = "28.0.0"
minSdk = "21"
targetSdk = "21"
compileSdk = "TiramisuPrivacySandbox"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
support-annotations = { module = "com.android.support:support-annotations", version.ref = "supportAnnotations" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }